m<-martix(c(1,2,3,4,5,6),ncol=2)
IQR(usedcars$price)
quantile(usedcars$price)
quantile(usedcars$price,probs = c(0.01,0.99))
quantile(usedcars$price,seq(from = 0,to=1,by=0.2))
boxplot(usedcars$price,main="box plot of used car price",ylab="price($)")
hist(usedcars$price,main="histogram of used car price",xlab="price($)")
var(usedcars$price)
sd(usedcars$price)
table(usedcars$year)
table(usedcars$color)
prop.table((table(usedcars$model)))*100
plot(x=usedcars$mileage,y=usedcars$price,main="Scattterplot of price vs Milege",xlab = "Miledge(ml.)",ylab = "Price($)")
usedcars$conservative<-usedcars$color %in% c("black","gray","silver","white")
table(usedcars$conservative)
install.packages("gmodels")
CrossTable(x = usedcars$model, y = usedcars$conservative)

library(ggplot2)
ggplot(housing.df) + geom_point(aes(x=LSTAT , y=MEDV),color="navy",alpha=0.7)
data.for.plot <- aggregate(housing.df$MEDV, by = list(housing.df$CHAS),FUN = mean)
names(data.for.plot)<-c("CHAS","MenaMEDV")
barplot(data.for.plot$meanEDV), names.arg = data.for.plot$CHAS)
